# Generated by Django 5.0.6 on 2024-05-29 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departementos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Numero_Telefono', models.CharField(max_length=10)),
                ('Fecha_Contratacion', models.DateField()),
                ('Cargo', models.CharField(max_length=50)),
                ('Salario', models.FloatField()),
                ('Departamento_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departementos.departamentomodels')),
            ],
        ),
    ]
