# Generated by Django 5.0.6 on 2024-05-29 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departementos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Departamento_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departementos.departamentomodels')),
            ],
        ),
    ]
